blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Ask a Question
    url: https://github.com/AEI-Digital-Co-Ltd/.github/discussions
    about: "Please ask questions in GitHub Discussions instead of issues."
